[package]
name = "bondsbot"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
reqwest = { version = "0.12.23", features = ["blocking"] }
scraper = "0.24.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.143"
